### ISSUE TITLE
Include JVM Parameters and Settings in Initial Configuration Log

### ISSUE THREAD

**Issue by zhongyuan17** [baidu/bifromq#48]
Currently, bifromq logs the initial configuration at the start of the program, which is very helpful. 
However, it would be even more beneficial if the log could also include JVM parameters and initial settings. 
This enhancement would provide a more comprehensive overview of the runtime environment, aiding in troubleshooting and configuration analysis.

**Comment by popduke** [comment]
close with 368ebf00353e526e6e078b2945a30260f2e01e18
